# -*- coding: utf-8 -*-
"""08/01/2025

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xr17lu8y0J1xb3Tv4q6vo0yqRmiW9ASq
"""

a = ['foo','bar','baz','qux','quux','corge']
print(a)
a [2] = 10
print(a)

a = ['foo','bar','baz','qux','quux','corge']
a[-1]=10
#b= list(a)
b = a[::]
print(id(a))
print(id(b))

l1 = list(range(1, 11))
print(l1)

l1 = list(range(10))
l2 = [i*10 for i in l1]
print(l2)

l1 = list(range(1, 31, 3))
l2 = [(i+1) * 3 for i in l1 if i%4 < 2]
print(l2)
print(l1)

l1 = ["A","B", "C", "D", "E", "F"]
l2 = l1.append("G")
l1 [0] = "Z"
l3 = l1.remove("C")
print(l1)

aprobados = []
desaprobados = []

while True:
  nota = int(input("Ingrese la nota del alumno: "))
  if nota >= 11:
    aprobados.append(nota)
  else:
    desaprobados.append(nota)

    continuar = input("¿Desea ingresar otra nota? (Si/SÍ/si para continuar): ")
    if continuar.lower() != "si":
        break

print("Notas aprobadas:", aprobados)
print("Notas desaprobadas:", desaprobados)

def mi_funcion (nombre, msj='hola'):
  print(msj, nombre)

mi_funcion('Juan')
mi_funcion('Juan', 'Chao')

def sumar(*tupla):
  suma=0
  for i in tupla:
    suma = suma + i
  return suma

valor = sumar(1,2,3,4,5)
print(valor)
sumar(1,2,3,4,5,6,7,8,9,10,11)

def funcion_one():
  x = 10
  print(x)
  def inner_func():
    print(x)
    inner_func()
funcion_one()

soles = int(input("Ingrese la cantidad de soles: "))
def cambio_dolares(soles):
  cambio= soles * 0.26
  def cambio_euros(soles):
    cambio = soles * 0.50
  return cambio_dolares

lista = [1, 2, 3, 4, 5]
lista_cortada = lista[1:4]
lista_cortada2 = lista[:]
lista_cortada3 = lista[0:2]
lista_cortada4 = lista[:2]
lista_cortada5 = lista[2:]
print(lista_cortada)
print(lista_cortada2)
print(lista_cortada3)
print(lista_cortada4)
print(lista_cortada5)

tupla = [1,2,3,4,5,6,7,8,9,10,12]
numero = int(input("Ingrese un numero: "))
if numero in tupla:
  print("El numero esta en la tupla")
else:
  print("El numero no esta en la tupla")